version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'joker-db'
       MYSQL_USER: 'ridler'
       MYSQL_PASSWORD: 'jokebot3000'
       MYSQL_ROOT_PASSWORD: 'jokebot3000'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/jokebot
    ports:
      - "8000:8000"
    depends_on:
      - db