# Generated by Django 2.2.12 on 2020-04-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whos_there', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=200)),
            ],
        ),
    ]
